"""Learning to rank from scratch: metrics, three loss families, and unbiased learning from clicks."""

from .data import (
    ClickLog,
    Dataset,
    Document,
    Query,
    TRUE_WEIGHTS,
    bm25_ranker,
    click_through_rates,
    estimate_propensities,
    examination_probability,
    feature_ranker,
    make_dataset,
    random_ranker,
    relevance_probability,
    simulate_clicks,
)
from .metrics import (
    average_precision,
    dcg,
    delta_ndcg,
    evaluate,
    expected_reciprocal_rank,
    mean_ndcg,
    mrr,
    ndcg,
    precision_at_k,
    score_spread,
)
from .models import (
    LinearScorer,
    TrainingLog,
    oracle_scorer,
    sigmoid,
    train_from_clicks,
    train_pairwise,
    train_pointwise,
)

__all__ = [
    "ClickLog",
    "Dataset",
    "Document",
    "LinearScorer",
    "Query",
    "TRUE_WEIGHTS",
    "TrainingLog",
    "average_precision",
    "bm25_ranker",
    "click_through_rates",
    "dcg",
    "delta_ndcg",
    "estimate_propensities",
    "evaluate",
    "examination_probability",
    "expected_reciprocal_rank",
    "feature_ranker",
    "make_dataset",
    "mean_ndcg",
    "mrr",
    "ndcg",
    "oracle_scorer",
    "precision_at_k",
    "random_ranker",
    "relevance_probability",
    "score_spread",
    "sigmoid",
    "simulate_clicks",
    "train_from_clicks",
    "train_pairwise",
    "train_pointwise",
]

__version__ = "0.1.0"
